//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntaTema
    {
        public int PreguntaTemasID { get; set; }
        public int PreguntaID { get; set; }
        public int TemaID { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
        public virtual Tema Tema { get; set; }
    }
}
